name: backend-CI
on:
  push: {}
  pull_request: {}

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"

      - name: Install dependencies
        run: |
          cd backend
          go mod download

      - name: Build
        run: |
          cd backend
          go build -v ./...

      - name: Show files
        run: |
          cd backend
          ls -a

      - name: Setup Go for Linting
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          working-directory: backend

      - name: Test with the Go CLI
        run: |
          cd backend
          go test ./...
