name: backend-CI
on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Install dependencies
        run: |
          cd backend
          go mod download
      - name: Build
        run: |
          cd backend
          go build -v ./...
      - name: Test with the Go CLI
        run: go test
