name: Unit Tests

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download
      - name: Test
        run: go test ./...